var app = angular.module('Upwave', []);

app.controller("MainController", function($scope){
	$scope.card1 = "instagram";
	$scope.card2 = "googleplus";
	$scope.card3 = "hamburger";
	$scope.card4 = "hln";
	$scope.card5 = "close";
	$scope.glyphs = ["add-collection",
					"anyone",
					"anywhere",
					"arrow-down",
					"arrow-left",
					"arrow-right",
					"arrow-up",
					"arrow2-right",
					"article",
					"brain",
					"challenge",
					"check",
					"close",
					"collections",
					"delete-collection",
					"email",
					"facebook",
					"facebook2",
					"gallery",
					"googleplus",
					"group",
					"hamburger",
					"hln",
					"indoors",
					"inspiration",
					"instagram",
					"justforu",
					"like",
					"linkedin",
					"maintenance",
					"multi-part",
					"oneoff",
					"outdoors",
					"padlocked",
					"padunlocked",
					"pinterest",
					"pinterest2",
					"profile",
					"questionmark",
					"recipe",
					"search",
					"settings",
					"share",
					"solo",
					"tips",
					"trophy",
					"tumblr",
					"twitter",
					"twitter2",
					"upwave",
					"upwave2",
					"uview",
					"video",
					"wave-arrow",
					"youtube"];
});